// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "MT4 Trading API",
	Description: "MT4 Trading System API with WebSocket real-time push",
}

type s struct{}

func (s *s) ReadDoc() string {
	return `{
    "swagger": "2.0",
    "info": {
        "description": "MT4 Trading System API with WebSocket real-time push",
        "title": "MT4 Trading API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {}
}`
}

func init() {
	// swag.Register(swag.Name, &s{})
}
